package dbWrapper;

import java.util.Set;
import java.util.HashSet;
import java.util.UUID;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

// TODO: Change back from test
@DynamoDBTable(tableName="InvertedDataTest")
public class InvertedNode {

    public String id;
    public String key;
    public String value;
    
    public InvertedNode() {
        this("","");
    }

    public InvertedNode(String key, String value) {
        this.key = key;
        this.value = value;
        this.id = UUID.randomUUID().toString();
    }

    @DynamoDBHashKey(attributeName="Id")
    @DynamoDBAutoGeneratedKey
    public String getId() { return id;}
    public void setId(String id) {this.id = id;}

    @DynamoDBAttribute(attributeName="NodeKey")
    public String getNodeKey() {return this.key;}
    public void setNodeKey(String key) {this.key = key;}

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "NodeValue-Index", attributeName="NodeValue")
    public String getNodeValue() {return value; }
    public void setNodeValue(String value) { this.value = value; }

    public String toString() {
        return this.key + ": " + this.value;
    }
}